apiVersion: v1
kind: Service
metadata:
  name: stock-market-service-kotlin-service
spec:
  selector:
    app: stock-market-service-kotlin
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer