apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-kotlin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-kotlin
  template:
    metadata:
      labels:
        app: user-service-kotlin
    spec:
      containers:
        - name: user-service-kotlin
          image: mmihailovic/user-service-kotlin:latest
          ports:
            - containerPort: 8080